amcl:
  ros__parameters:
    use_sim_time: false

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: "/scan"

    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    tf_broadcast: true
    transform_tolerance: 0.2

    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: -1.0
    max_beams: 60
    sigma_hit: 0.2
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    lambda_short: 0.1
    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    max_particles: 2000
    min_particles: 500
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    save_pose_rate: 0.5
    update_min_a: 0.2
    update_min_d: 0.25

    # Die Startpose wird nach dem Start über "2D Pose Estimate" in RViz gesetzt.
    always_reset_initial_pose: false
    set_initial_pose: false
