edges:
- - FlurEnde
  - Eingang105
- - Eingang105
  - RaumFront
- - RaumFront
  - 105Mitte
- - 105Mitte
  - Ende105
- - FlurEnde
  - FlurLab
- - FlurLab
  - EinganLab
- - EinganLab
  - LabTuer
- - LabTuer
  - Tafel
- - LabTuer
  - EckeLab
- - EckeLab
  - FensterLab
- - Tafel
  - Pult
- - Pult
  - FensterLab
- - FlurLab
  - FlurMitte
- - FlurMitte
  - Raum107
- - Raum109
  - Raum107
- - FlurMitte
  - Raum109
- - FlurMitte
  - FlurEcke
- - FlurEcke
  - Raum109
- - Raum107
  - FlurEcke
