nodes:
  FlurEnde:
    x: -0.646
    y: 11.6
    is_door: false
  RaumFront:
    x: -0.129
    y: 16.404
    is_door: false
  Eingang105:
    x: -0.455
    y: 14.457
    is_door: true
  105Mitte:
    x: 2.993
    y: 17.653
    is_door: false
  Ende105:
    x: 5.861
    y: 17.653
    is_door: false
  EinganLab:
    x: 4.728
    y: 8.286
    is_door: true
  FlurLab:
    x: 4.959
    y: 11.154
    is_door: false
  LabTuer:
    x: 4.173
    y: 7.43
    is_door: false
  FlurMitte:
    x: 9.03
    y: 10.899
    is_door: false
  Raum107:
    x: 11.366
    y: 12.31
    is_door: false
  Raum109:
    x: 11.181
    y: 9.951
    is_door: false
  FlurEcke:
    x: 7.943
    y: 8.91
    is_door: false
  Tafel:
    x: -1.262
    y: 6.805
    is_door: false
  Pult:
    x: -1.771
    y: 3.22
    is_door: false
  EckeLab:
    x: 3.387
    y: 0.584
    is_door: false
  FensterLab:
    x: -1.632
    y: 0.838
    is_door: false
